// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "4c06fd213c909c409d260d236f569d6e"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"51968410ef3ab9a57d06148570a5c521": "1f8b08000000000000ff2a484cce4e4c4f554849cce7e24a2bcd4b5670c9d7d0ace6e2aa05040000ffffd318594c1a000000",
		"6628c8846518561e7f8cb2d90372388f": "1f8b08000000000000ff54ccbb0e82301406e0b9ff539c3018300abbb3b38b4f50cab13642db9cb65e42787707d1c4f5fb2f519b9bb64c89e5ee0c036e8a4132d5509575f95afad684a94ba54f46fb3d3fe31884e507712cd6f92ee520da728506c8afc874fefc51ca524ca6196aa0b5d41e75c0025c8a3774e247fd9734b4fd6e6728e15cc4d366a5194a0d071a76500b16bc030000ffff50dafc17bd000000",
		"82fad82413ab1008a0fe459e2727c0ba": "1f8b08000000000000ff9c54cf8eda3c103fe3a718e5f029417ca67d80bd1490da032bba2bb587d50a19673658044f349e50aa28ef5e19d800454a77f73460cfef8f7f9eb83276630a84a6d1f7668b6dab94db56c402a91a24859375bdd296b6e350af8235fe7fdc57253172b7509575e1fc3808b12930791f8aa916e4440100244da3e7942f8cacdbb6f3335e8b54bd0d0179e7ec8df29aaa50b1f3c53847ebb6a64c54a6d4ce3004dec1f084d28fc7aa94fcae0e31cc299f942684b685205c5b81460d72389d4f4f0da956a997da5bb8c75f6906c36b50a3068c52b387ffae369ab6c3a5e62f5006dfbc93a9a1f44a288b64d1ed1dbcda8d9246e7991a189dc31de4f1c7dc156c04d3ec5f0a5f45aa3483a7e763ee3afe3ffb8d49eb87c34e1a78d7cbb660b218c26c2fec7c70365dc2f0d5f99792ec6604172b5ddb68094fcfddea0ebd6480ccc417b17957be4539826f552f4563c76809a7ebd7d3637db760972e347d6d3f9083239f66716c9c2f2e04924ffa73d2877d8c5f05bb159ef3cc0e4145a2e630fc6ff37a263ac4f331929937ab329e7745545e01856bec434ec8877a5b8923ffbdc61a3f7a0a9407cc5d581095e9124e6fc6f2f866e86e2b5e480fcd6c8ff627f10639b5e405f7a227c73a3a5dd1b93a2fc82fc662d39ee7e3c6f09f000000ffff6fe1d3872d050000",
		"94dc25527ed8ecf87f52e0fb342e520d": "1f8b08000000000000ff6490c14a2c311045d75d5f51643533cc4b7fc1dbbb51645cb8101799584e07bb9358556995907f979e6e047115b8b9f71ca8ecfc9bbb100eaa19204c39b1e20e3a53abbd4d2ff74e87d66ab5776ea2d67a219e8327038888e612742867ebd3d44b398b77f11f7de63131f14f90c77209b1e7549478db45d27e111ad803cc8e17a1cc1e0f1bde3eaceff2fd5aa2c7d375bd933f8d3d3e3daf687ba39ab1aea0ff28d03169e1f8bb50a1ebaa51123547942f519ada11ba066d33add9eee37a107b22c9290a3d7250e223321eb6fcbd90e81e8939f162dd64318cd0be030000ffffed0603d154010000",
		"f75dfcae861bebb91cdce358a8722c73": "1f8b08000000000000ff2a484cce4e4c4f55c8cd4f49cde1e22aa92c4855a8aed6f3cd4f71ce492c2eaead55282e292a4d2e51a8e6aae502040000ffffcb815bad2d000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("all", "./templates/plugin")
		b.SetResolver("dao/dao.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "51968410ef3ab9a57d06148570a5c521"})
		b.SetResolver("http/http.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "94dc25527ed8ecf87f52e0fb342e520d"})
		b.SetResolver("main.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "82fad82413ab1008a0fe459e2727c0ba"})
		b.SetResolver("model/model.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "f75dfcae861bebb91cdce358a8722c73"})
		b.SetResolver("service/service.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "6628c8846518561e7f8cb2d90372388f"})
		}()

	return nil
}()
